### PR TITLE
add:chapter3

### PR DESCRIPTION
**Pull request by shmuhammadd**
This is chapter 3 presentation: stop words

### CODE REVIEW

**Comment by shmuhammadd** [comment]
@jonthegeek  I am not sure what to do. It seems is failing ! What can I do?

**Comment by jonthegeek** [comment]
> @jonthegeek I am not sure what to do. It seems is failing ! What can I do?

I'm working on it! One moment please!

**Comment by shmuhammadd** [comment]
> > @jonthegeek I am not sure what to do. It seems is failing ! What can I do?
> 
> I'm working on it! One moment please!

Thank you @jonthegeek

**Review by jonthegeek — APPROVED** [review]
Re-approving after refreshing.

**Review by shmuhammadd — COMMENTED** [review]
Thanks

**Pull request merged**
